// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfjjmawasinkzbiiruws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mamptYXdhc2lua3piaWlydXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3MDE2MTQsImV4cCI6MjA4OTI3NzYxNH0.beV7hje_7RKfPNtX_rYLIp7PEwucLV6rLFPJKTzjK2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});